version: "3.9"
services:
    api:
        env_file: ./api/api.env
        image: "amiradar/tiny-url.api"
        ports:
            - "3001:8080"
            
    user-service:
        env_file: ./userService/userService.env
        image: "amiradar/tiny-url.user-service"
        
    url-service:
        env_file: ./urlService/urlService.env
        image: "amiradar/tiny-url.url-service"

    authentication:
        env_file: ./authentication/auth.env
        image: "amiradar/tiny-url.authentication"

    email-consume:
        env_file: ./emailConsume/emailConsume.env
        image: "amiradar/tiny-url.email-consume"        