POST http://localhost:8080/api/signUp
Content-Type: application/json

{
    "userEmail": "yamit@gmail.com",
    "userFullName": "yamit adar",
    "userPassword": "yamit123"
}

###

POST http://localhost:8080/api/logIn
Content-Type: application/json

{
    "userEmail": "amir@gmail.com",
    "userPassword": "amir123"
}

###

POST http://localhost:8090/api/user
Content-Type: application/json

{
    "userEmail": "reut@gmail.com",
    "userFullName": "reut adar",
    "userPassword": "reut123"
}

###

POST http://localhost:8070/api/url
Content-Type: application/json

{
    "LongURL": "https://www.yamitWeb_3_.co.il/search?hl=en&sxsrf=ALeKk01Hm0XbmR3tC-JbBWVcs4u78DNVIA%3A1609320845871&source=hp&ei=jUnsX5_kMofmU4Ljgjg&q=amir&oq=amir&gs4dUDCAc&uact=5",
    "Email": "yamit@gmail.com"
}

###

GET http://localhost:8080/api/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYW1pckBnbWFpbC5jb20iLCJpYXQiOjE2MTA1NTU0MzV9.-1UTzKs2kgObaoDRbzpYAAdRaqKoa1Vl62BOlzBk1qY


###