
//working!
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "userEmail": "000@gmail.com",
    "userFullName": "vvv sh",
    "userPassword": "000"
}

###
//working
POST http://localhost:3001/api/auth/logIn
Content-Type: application/json

{
    "userEmail": "aaa@gmail.com",
    "userPassword": "aaa"
}


###
//working
//create new short Url
POST http://localhost:3001/api/auth/createUrl
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUBnbWFpbC5jb20iLCJpYXQiOjE2MTIyNTcyOTV9.Gn5-ivG65XEnrvHZmqb__igl50R6-ls1jdnpom-g5BQ

{
    "LongURL": "https://stackoverflowaa.com/questions/42766446/how-to-handle-error-er-dup-entry-duplicate-entry-in-nodejs",
    "Email": "aaa@gmail.com",
    "IsPrivate": true
}

###
//working
//public url 
GET http://localhost:3001/api/url/25

###
//working

//private url Work!
GET http://localhost:3001/api/url/25
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUBnbWFpbC5jb20iLCJpYXQiOjE2MTIyNTcyOTV9.Gn5-ivG65XEnrvHZmqb__igl50R6-ls1jdnpom-g5BQ

###



# GET http://localhost:3001/api/list
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoieWFtaXRAZ21haWwuY29tIiwiaWF0IjoxNjEwNjMyMTM0fQ.hdn23_xrklz3BYD_XU61aS3M1cVPtUp140XmNtOAycE

# ###


