on:
  push:
    branches:
      - main

name: ci & cd

jobs:
  build-api:
    name: build-api
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build, tag, and push image to Docker Hub
      id: build-image
      run: 
        cd api
        docker login --username=amiradar --password=amiradar123
        docker build -t amiradar/tiny-url.api .
        docker push amiradar/tiny-url.api

  build-url-service:
    name: build-url-service
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build, tag, and push image to Docker Hub
      id: build-image
      run: 
        cd url-service
        docker login --username=amiradar --password=amiradar123
        docker build -t amiradar/tiny-url.url-service .
        docker push amiradar/tiny-url.url-service


  build-user-service:
    name: build-user-service
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build, tag, and push image to Docker Hub
      id: build-image
      run: |
        cd user-service
        docker login --username=amiradar --password=amiradar123
        docker build -t amiradar/tiny-url.user-service .
        docker push amiradar/tiny-url.user-service


  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [build-api, build-url-service, build-user-service]

    steps:
    - name: call deploy server
      uses: fjogeleit/http-request-action@master
      with:
          url: 'http://ec2-3-133-84-51.us-east-2.compute.amazonaws.com:3456/api/deploy'
          method: 'POST'
    